<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.6" />
  </ItemGroup>
</Project>
